version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: UserIdentityAccess.API/Dockerfile
    container_name: useridentityaccess_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=IDENTITY_ACCESS_DB;User Id=SA;Password=reallyStrongPwd123;
    depends_on:
      - db
    ports:
      - "5002:5000"
      - "5003:5001"
    restart: always
    networks:
      - mynetwork
    command: >
      sh -c "dotnet ef database update --project UserIdentityAccess.Infrastructure/ &&
             dotnet UserIdentityAccess.API.dll"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: useridentityacces_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always
    networks:
      - mynetwork

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: useridentityaccess_db
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
