import { DataGridProperties } from './properties/data-grid';

export const defaultDataGridProperties: DataGridProperties = {
  allowColumnReordering: true,
  allowColumnResizing: true,
  cellHintEnabled: true,
  columnChooserEnabled: true,
  columnFixingEnabled: true,
  columnHidingEnabled: false,
  exportEnabled: true,
  allowExportSelectedData: true,
  filterRowVisible: true,
  groupingAutoExpandAll: true,
  groupingContextMenuEnabled: true,
  groupPanelVisible: true,
  headerFilterVisible: true,
  pagerShowInfo: true,
  pagingEnabled: true,
  pagingPageSize: 0,
  rowAlternationEnabled: true,
  searchPanelVisible: true,
  selectionMode: "",
  showBorders: true,
  showColumnHeaders: true,
  showColumnLines: true,
  stateStoringEnabled: true,
  wordWrapEnabled: true,
  editMode: "Row",
};
